idf_component_register(
    SRCS 
        "main.c"
        "main_app_entry.c"
        "rtos.c"
        "bt.c"
        "bt_request.c"
        "settings.c"
        "console/console.c"
        "console/console_cmd.c"
        "console/console_cmd_handles.c"
        "display/display.c"
        "display/display_input.c"
        "display/display_ll.c"
        "display/display_lvgl.c"
        "display/display_request.c"
        "display/display_calibration.c"
        "display/screens/screen.c"
        "display/screens/screen_display_calibration.c"
        "display/screens/screen_main.c"
    INCLUDE_DIRS "."
    REQUIRES 
        "esp_lcd"
        "esp_lcd_ili9341"
        "esp_lcd_touch"
        "esp_lcd_touch_xpt2046"
        "lvgl"
        "nvs_flash"
        "bt"
        )
